# Downsampling parameters
voxel_leaf_size: 0.01

# Depth filter parameters
min_depth: 1.1
max_depth: 5.0

# LCCP segmentation parameters
voxel_resolution: 0.03
seed_resolution: 0.15
color_importance: 0.1
spatial_importance: 1.0
normal_importance: 5.0
concavity_tolerance_threshold: 15.0
use_smoothness_check: true
smoothness_threshold: 0.15
k_factor: 0.5
min_segment_size: 500
use_supervoxel_refinement: true
small_segment_threshold_percent: 1.0
use_single_camera_transform: false
supervoxel_refinement_iterations: 2